'use client'
// import type { Metadata } from "next";

import { Provider } from "react-redux";
import { store } from "./store";

import styled from "styled-components";
import StyledComponentsRegistry from "@/lib/registry";

const Layout = styled.div`
  max-width: 800px;
  margin: auto;
`;

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <Layout>
            <Provider store={store}>
              {children}
            </Provider>
          </Layout>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
