import StyledComponentsRegistry from "@/lib/styled-components-registry";
import StoreProvider from "../lib/store-provider";
import "./global.css";

import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StyledComponentsRegistry>
          <StoreProvider>
            <div className="main">{children}</div>
          </StoreProvider>
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
